spring.application.name=BulkDataImportSystem

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bulk_import_db
spring.datasource.username=root
spring.datasource.password=Shaikali@270

# SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true

# File Upload Limits
spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size=100MB

# JDBC Driver Optimization
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Hibernate Batch Processing
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Logging
logging.level.root=INFO
logging.level.com.shaik.bulkimport=DEBUG
logging.file.name=logs/bulk-import.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n



spring.output.ansi.enabled=ALWAYS


